"""Export original templates, editable JSON blueprints and a typed native-field allowlist."""
import ast
import importlib.util
import json
from pathlib import Path

spec = importlib.util.spec_from_file_location('blendfile', 'tooling/asset-pack/vendor/blendfile.py')
blendfile = importlib.util.module_from_spec(spec)
spec.loader.exec_module(blendfile)
audit = json.loads(Path('research/reforged/output/components-audit.json').read_text())
primitive_kinds = {'float': 'F', 'int': 'I', 'short': 'H', 'char': 'B'}
field_tables = {}
needed = {'Object', 'bProperty', 'bSensor', 'bController', 'bActuator'}
for scene in audit['scenes'].values():
    for obj in scene['objects']:
        for bricks in obj['logic'].values():
            needed.update(brick['payload_type'] for brick in bricks if 'payload_type' in brick)
with blendfile.open_blend('assets/original/RyansHardestGame.blend') as game:
    for name in sorted(needed):
        fields = game.structs[game.sdna_index_from_id[name.encode()]].fields
        table = {}
        for field in fields:
            key = field.dna_name.name_only.decode()
            datatype = field.dna_type.dna_type_id.decode()
            count = field.dna_name.array_size
            if key.startswith('pad') or key in {'next','prev','mynew','totlinks','totslinks'}:
                continue
            if field.dna_name.is_pointer:
                if name not in {'Object','bSensor','bController','bActuator','bProperty'} and datatype in {'Object','Scene','Mesh','bSound'}:
                    table[key] = {'kind':'P','count':1,'target':datatype}
            elif datatype in primitive_kinds:
                table[key] = {'kind':'S' if datatype=='char' and count>1 else primitive_kinds[datatype], 'count':count}
        field_tables[name] = table


def readable_fields(raw, typename):
    """
    Convert audited DNA keys to editable fields, excluding addresses and padding.

    >>> # readable_fields({"b'freq'": 5, "b'next'": 123}, 'bSensor') == {'freq': 5}
    """
    result = {}
    for encoded, value in raw.items():
        key = ast.literal_eval(encoded).decode()
        descriptor = field_tables[typename].get(key)
        if descriptor and descriptor['kind'] != 'P':
            if descriptor['kind']=='B' and isinstance(value,str):
                value = ord(value) if value else 0
            result[key] = value
    return result


# Runtime offsets come from C's offsetof, never from untrusted JSON or host pointer sizes.
rows = ['// Generated by tooling/reforged/export_library.py from authoritative SDNA.',
        'static const Field fields[] = {']
for typename, table in field_tables.items():
    for key, descriptor in table.items():
        rows.append('    {"%s", "%s", offsetof(%s, %s), \'%s\', %d, "%s"},' % (
            typename,key,typename,key,descriptor['kind'],descriptor['count'],descriptor.get('target','')))
rows.append('};\n')
Path('runtime/reforged-fields.inc').write_text('\n'.join(rows))

blueprints = []
for name, scene in audit['scenes'].items():
    objects=[]
    for obj in scene['objects']:
        logic={}
        for kind, bricks in obj['logic'].items():
            if kind=='prop':
                continue
            logic[kind]=[]
            for brick in bricks:
                item={'name':brick['name'],'settings':readable_fields(brick['fields'],brick['dna'])}
                # Type/name identify the original brick. They are not interchangeable payload layouts.
                for key in ['name','type','otype']:
                    item['settings'].pop(key,None)
                if kind in {'sensors','controllers'}:
                    item['links']=brick.get('links',[])
                if 'payload_type' in brick:
                    item['payloadType']=brick['payload_type']
                    item['payload']=readable_fields(brick['payload'],brick['payload_type'])
                    item['references']={ast.literal_eval(k).decode():v for k,v in brick['references'].items()}
                logic[kind].append(item)
        objects.append({'id':obj['name'],'source':obj['name'],'position':obj['loc'],
                        'rotation':obj['rotation'],'scale':obj['scale'],'parent':obj['parent'],
                        'active':obj['active'],'logic':logic})
    spacing=200/31
    instance_ids={obj['id'] for obj in objects}
    for obj in objects:
        for bricks in obj['logic'].values():
            for brick in bricks:
                for field,target in list(brick.get('references',{}).items()):
                    if target.startswith('OB') and target not in instance_ids:
                        brick['references'][field]='@'+target
    level={'format':'reforged','version':1,'name':name[2:]+' — editable original',
           'scene':name[2:],'camera':scene['camera'],
           'grid':{'spacing':spacing,'subdivisions':1,'snap':True,'origin':[0,0]},
           'objects':objects}
    path=Path('web/reforged/levels')/(name[2:].replace(' ','-')+'.json')
    path.write_text(json.dumps(level,separators=(',',':'))+'\n')
    blueprints.append({'scene':name[2:],'url':'levels/'+path.name,'objects':len(objects)})
    print(path, len(objects),'editable object instances')

library={'version':1,'blueprints':blueprints,'fields':field_tables,
         'objects':{o['name']:o for s in audit['scenes'].values() for o in s['objects']},
         'meshes':audit['meshes'],'materials':audit['materials']}
# The raw pointer-bearing audit is research-only; the browser library needs appearance metadata.
for obj in library['objects'].values():
    obj['properties']=[p['name'] for p in obj.pop('logic')['prop']]
Path('web/reforged/library.json').write_text(json.dumps(library,separators=(',',':'))+'\n')
print('Exported',len(library['objects']),'original templates and',len(library['meshes']),'meshes')
payloads = {}
original_audit = json.loads(Path('research/reforged/output/components-audit.json').read_text())
for scene in original_audit['scenes'].values():
    for obj in scene['objects']:
        for kind, code in [('sensors',0),('actuators',2)]:
            for brick in obj['logic'][kind]:
                if 'payload_type' in brick:
                    key=(code,brick['fields']["b'type'"])
                    assert key not in payloads or payloads[key]==brick['payload_type']
                    payloads[key]=brick['payload_type']
rows=['const char *payloadType(int kind,int type) {']
for (kind,code),name in sorted(payloads.items()):
    rows.append('    if(kind==%d && type==%d)return "%s";'%(kind,code,name))
rows.extend(['    return NULL;','}\n'])
Path('runtime/reforged-payloads.inc').write_text('\n'.join(rows))
